# Generated by Django 2.2.2 on 2019-09-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNews',
            fields=[
                ('adminNewsID', models.AutoField(primary_key=True, serialize=False, verbose_name='admin news ID')),
                ('adminNewsText', models.CharField(max_length=10000, verbose_name='admin news text')),
                ('adminNewsDate', models.DateTimeField(auto_now=True, verbose_name='admin news publish date')),
                ('adminNewsUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
