# Generated by Django 2.2.2 on 2019-09-24 19:41

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totalComments',
            field=models.IntegerField(default=0, verbose_name='total comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='totalMods',
            field=models.IntegerField(default=0, verbose_name='total mods'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatarID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='avatar id')),
                ('avatarTime', models.DateTimeField(auto_now=True)),
                ('avatarImage', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=accounts.models.avatar_path, verbose_name='avatar image')),
                ('avatarUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatarUser', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
