# Generated by Django 2.2.2 on 2019-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avatar_avatarapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='avatarIP',
            field=models.CharField(default=0, max_length=100, verbose_name='mod user ip address'),
            preserve_default=False,
        ),
    ]
