# Generated by Django 2.2.2 on 2019-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='modUploadURL',
            field=models.URLField(help_text='Only Google Drive and MEGA are currently supported.', max_length=1000, verbose_name='Mod Upload Destination'),
        ),
    ]
