# Generated by Django 2.2.2 on 2019-09-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_auto_20190925_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='modIP',
            field=models.CharField(default=0, max_length=100, verbose_name='mod user ip address'),
            preserve_default=False,
        ),
    ]
