# Generated by Django 2.2.2 on 2019-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0006_mod_modip'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsIP',
            field=models.CharField(default=0, max_length=100, verbose_name='news user ip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod',
            name='modApproved',
            field=models.BooleanField(default=False, verbose_name='mod moderation approval'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='reviewApproved',
            field=models.BooleanField(default=False, verbose_name='review moderation approval'),
        ),
    ]
