# Generated by Django 2.2.2 on 2019-11-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0010_remove_mod_modapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedit',
            name='modEditID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
