# Generated by Django 2.2.2 on 2019-11-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0011_modedit_modeditid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modedit',
            name='modEditID',
        ),
    ]
