# Generated by Django 2.2.2 on 2019-11-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0012_remove_modedit_modeditid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modedit',
            old_name='modID',
            new_name='modEditID',
        ),
    ]
