# Generated by Django 2.2.2 on 2019-11-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0013_auto_20191125_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedit',
            name='modID',
            field=models.IntegerField(default=None, unique=True, verbose_name='mod id'),
        ),
        migrations.AlterField(
            model_name='modedit',
            name='modEditID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='mod edit id'),
        ),
    ]
