# Generated by Django 2.2.2 on 2019-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0014_auto_20191125_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='modApproved',
            field=models.BooleanField(default=True),
        ),
    ]
