# Generated by Django 2.2.2 on 2019-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0015_mod_modapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='modApproved',
        ),
        migrations.AddField(
            model_name='mod',
            name='modShow',
            field=models.BooleanField(default=True, verbose_name='Mod Show'),
        ),
    ]
