# Generated by Django 2.2.2 on 2019-11-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0016_auto_20191126_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modedit',
            name='modApproved',
        ),
    ]
