# Generated by Django 2.2.2 on 2019-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0018_auto_20191128_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modedit',
            name='modID',
            field=models.IntegerField(default=None, unique=True, verbose_name='mod id'),
        ),
    ]
