# Generated by Django 2.2 on 2019-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0020_mod_modedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedit',
            name='modApproved',
            field=models.BooleanField(default=True),
        ),
    ]
