# Generated by Django 2.2.10 on 2020-02-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod', '0024_auto_20200201_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditReviewRating',
            fields=[
                ('reviewEditId', models.AutoField(primary_key=True, serialize=False, verbose_name='review edit id')),
                ('reviewid', models.IntegerField(verbose_name='review id')),
                ('reviewDate', models.DateTimeField(auto_now_add=True, verbose_name='review date')),
                ('reviewComment', models.CharField(blank=True, max_length=10000, verbose_name='review comment')),
                ('reviewVotes', models.IntegerField(default=0, verbose_name='total votes for comment')),
                ('reviewApproved', models.BooleanField(default=False, verbose_name='review moderation approval')),
                ('reviewAuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewModID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewEditModID', to='mod.Mod')),
            ],
        ),
    ]
