# Generated by Django 2.2.10 on 2020-02-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0025_editreviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editreviewrating',
            name='reviewAuthorID',
        ),
        migrations.RemoveField(
            model_name='editreviewrating',
            name='reviewModID',
        ),
        migrations.RemoveField(
            model_name='editreviewrating',
            name='reviewVotes',
        ),
    ]
