# Generated by Django 2.2.10 on 2020-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0026_auto_20200214_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='reviewHasEdit',
            field=models.BooleanField(default=False, verbose_name='review has got edit'),
        ),
    ]
