# Generated by Django 2.2.10 on 2020-02-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0028_auto_20200219_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='modBest',
            field=models.BooleanField(default=False, verbose_name='best mod?'),
        ),
        migrations.AddField(
            model_name='mod',
            name='modRunnerUp',
            field=models.BooleanField(default=False, verbose_name='runner-up mod?'),
        ),
    ]
