# Generated by Django 2.2.10 on 2020-03-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0029_auto_20200220_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modedit',
            name='modBest',
        ),
        migrations.RemoveField(
            model_name='modedit',
            name='modRunnerUp',
        ),
    ]
