# Generated by Django 2.2.10 on 2020-03-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0030_auto_20200318_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='modBest',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='modRunnerUp',
        ),
    ]
