# Generated by Django 2.2.10 on 2020-07-28 11:39

import django.core.validators
from django.db import migrations, models
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0032_mod_modredditaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='modContact',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Owner Contact Info'),
        ),
        migrations.AddField(
            model_name='mod',
            name='modInternalNote',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Moderator Internal Notes'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='modUpload',
            field=models.FileField(blank=True, null=True, upload_to=mod.models.mod_directory_path_keep_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='modedit',
            name='modUpload',
            field=models.FileField(blank=True, null=True, upload_to=mod.models.mod_directory_path_keep_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])]),
        ),
    ]
