# Generated by Django 2.2.10 on 2020-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0033_auto_20200728_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedit',
            name='modContact',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Owner Contact Info'),
        ),
        migrations.AddField(
            model_name='modedit',
            name='modInternalNote',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Moderator Internal Notes'),
        ),
    ]
